### PR TITLE
tail call optimization

### PR DESCRIPTION
**Pull request by pbrinkmeier**
- [x] Right now the firm verifier complains about the graph this code generates, some debugging is necessary. It's late tho 🐞 
- [x] Add tests for different cases
  - Especially tail calls where the object changes. These should not be a problem, however it's better to err on the side of caution

### CODE REVIEW

**Comment by pbrinkmeier** [comment]
Just want to merge this so I don't have to rebase all the time.

**Comment by Garmelon** [comment]
I tried to get this to trigger with code like
```java
class Main {
	public static void main(String[] args) {
		Foo foo = new Foo();
		int i = System.in.read();

		System.out.println(foo.foo(i));

		foo.res = 12345;
		foo.bar(i);
		System.out.println(foo.res);
	}
}

class Foo {
	public int foo(int x) {
		if (x > 0) {
			return foo(x - 1);
		} else {
			return x;
		}
	}

	public int res;
	public void bar(int x) {
		if (x > 0) {
			foo(x - 1);
		} else {
			res = x;
		}
	}
}
```
but no tco graphs were dumped (other graphs were dumped successfully). Also `exec/Vector.java` seems to crash in `EscapeAnalsysisOptimization` due to recursion.

**Comment by Garmelon** [comment]
The escape analysis thing just needed a good rebasing.

**Comment by Garmelon** [comment]
Resolved cli flag conflicts

**Review by Garmelon — APPROVED** [review]

**Pull request merged**
